theme: jekyll-theme-cayman

title: Spatial-temporal Transformer-guided Diffusion based Data Augmentation for Efficient Skeleton-based Action Recognition
description: A novel denoising diffusion probabilistic model can synthesize human motions following the precise guidance of a spatial-temporal transformer (ST-Trans). <br /> (Preprinting)
